---
- name: Gestione e Backup Huawei NetEngine 8000 via NETCONF
  hosts: all
  gather_facts: no

  tasks:
    - name: Recupera la configurazione di sistema (Running Config)
      ansible.netcommon.netconf_get:
        source: running
        display: xml
      register: netconf_output

    - name: Salva la configurazione XML ricevuta sul server
      ansible.builtin.copy:
        content: "{{ netconf_output.output }}"
        dest: "./backups/{{ inventory_hostname }}_netconf_config.xml"

