- name: Playbook per modificare interfaccia Huawei
  hosts: NE8000-F1A
  connection: ansible.netcommon.netconf
  gather_facts: no

  tasks:
    - name: Applica configurazione su interfaccia 25GE0/1/40 via RPC
      ansible.netcommon.netconf_rpc:
        rpc: edit-config
        content: |
          <target>
            <candidate/>
          </target>
          <config>
            <ifm xmlns="urn:huawei:yang:huawei-ifm">
              <interfaces>
                <interface>
                  <name>25GE0/1/40</name>
                  <description>Backbone 25G gestito via Semaphore</description>
                </interface>
              </interfaces>
            </ifm>
          </config>



