- name : Playbook per change IF
  hosts: NE8000-F1A
  connection: netconf
  gather_facts: no

  tasks:
    - name: Display interface 25GE0/1/40
      netconf_config:
        config: |
          <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
            <interface>
              <name>25GE0/1/40</name>
              <description>Collegamento via Semaphore UI</description>
            </interface>
          </interfaces>
      register: result


