- name: Playbook per creazione e descrizione Subinterface via NETCONF
  hosts: NE8000-F1A
  connection: netconf
  gather_facts: no

  tasks:
    - name: Crea subinterface 25GE0/1/42.100, descrizione e VLAN (RPC Certificato)
      ansible.netcommon.netconf_config:
        target: candidate
        content: |
          <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
            
            <ifm xmlns="urn:huawei:yang:huawei-ifm">
              <interfaces>
                <interface>
                  <name>25GE0/1/42.100</name>
                  <description>Subint creata da Semaphore UI</description>
                  
                  <ethernet xmlns="urn:huawei:yang:huawei-ethernet">
                    <l3-sub-interface>
                      <dot1q-termination>
                        <tag>none</tag>
                        <dot1q-vlans>
                          <dot1q-vlans>
                            <vlan-list>100</vlan-list>
                          </dot1q-vlans>
                        </dot1q-vlans>
                      </dot1q-termination>
                    </l3-sub-interface>
                  </ethernet>

                </interface>
              </interfaces>
            </ifm>

          </config>
      register: subint_result

    - name: Mostra esito creazione
      debug:
        var: subint_result









