all:
  hosts:
    NE8000-F1A:
      ansible_host: 10.15.12.1
  vars:
    ansible_connection: ansible.netcommon.netconf
    ansible_network_os: ansible.netcommon.default
    ansible_port: 830
    ansible_user: netconf
    ansible_password: NetAutomation2026
    # Forza Ansible a usare la password e a non cercare chiavi SSH sul server Semaphore
    ansible_ssh_lookup_keys: False
    ansible_ssh_auth_allow_backends: password


