- name: NETCONF playbook
  hosts: MY_HOST_NAME
  connection: netconf
  gather_facts: no
  tasks:
    - name: NETCONF RPC
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <bd xmlns="urn:huawei:yang:huawei-bd">
                <instances>
                  <instance>
                    <id>100</id>
                    <service-points>
                      <service-point xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge">
                        <interface-name>25GE0/1/40.200</interface-name>
                      </service-point>
                    </service-points>
                  </instance>
                </instances>
              </bd>
              <ifm xmlns="urn:huawei:yang:huawei-ifm">
                <interfaces>
                  <interface xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge">
                    <name>25GE0/1/40.200</name>
                    <class>sub-interface</class>
                    <l2-mode-enable>true</l2-mode-enable>
                    <ethernet xmlns="urn:huawei:yang:huawei-ethernet">
                      <l2-sub-interface nc:operation="merge">
                        <dot1q>
                          <vlans nc:operation="merge">
                            <vlan-list>200</vlan-list>
                          </vlans>
                        </dot1q>
                        <flow-action nc:operation="merge">
                          <action-type>map-1-to-1</action-type>
                          <out-vlan-id>100</out-vlan-id>
                        </flow-action>
                      </l2-sub-interface>
                    </ethernet>
                  </interface>
                </interfaces>
              </ifm>
            </config>
      register: result

    - name: Edit details for sub-interface
      debug:
        msg: "{{ result }}"
